# Disciplina: Teoria de Grafos

- Matriz de adjacências
- Número de vértices n
- Número de arestas e
- Grau de vértices d(G)

### Prof. Marcos W. Rodrigues

In [24]:
import numpy as np
import pandas as pd
from collections import defaultdict
import csv

In [25]:
folder = "graphs/"

In [ ]:
class Graph(object):


    """
    Initiate the graph with an adjancency matrix read from a csv file.
    """
    def __init__(self, file):
        df = pd.read_csv(folder+file, sep=';', header=0, engine='python')
        matrix = df.values
        
        self.n = len(matrix)

        self.init_AdjList(matrix)

    """
    Initialize the adjacency list.
    """
    def init_AdjList(self,matrix):
        self.adjList = defaultdict(list)

        for i in range(self.n):
            for j in range(self.n):
                if matrix[i][j] == 1:
                    self.adjList[i].append(j)

    def __len__(self):
        return self.n

    def add_edge(self, u, v):
        self.adjList[u].append(v)
        self.adjList[v].append(u)

    def remove_edge(self, u, v):
        self.adjList[u].remove(v)
        self.adjList[v].remove(u)
    
    def numVertices(self):
        return len(self.adjList)
    
    def numArestas(self):
        return(int (sum(len(adjacent) for adjacent in self.adjList.values()) / 2))
    
    def grausVertices(self):
        graus = {        }

        for v in self.adjList:
            graus[v] = len(self.adjList[v])

        return graus
    
    def hasParallelEdges(self):
        if any(len(adj) != len(set(adj)) for adj in self.adjList.values()):
            return True
        return False
    

    """
    Necessário tratar caso que haja loops, pois eles estão sendo contados como paralelos, o que é incorreto.
    """
    def parallelEdges(self):
        parallelEdges = {}
        for v in self.adjList:
            if len(self.adjList[v]) != len(set(self.adjList[v])):
                parallelEdges[v] = self.adjList[v]
        return parallelEdges
    
    def hasloopEdges(self):
        if any(v in adj for v, adj in self.adjList.items()):
            return True
        return False

    def loopEdges(self):
        loopEdges = {        }
        for v in self.adjList:
            if v in self.adjList[v]:
                loopEdges[v] = self.adjList[v]
        return loopEdges
    
    def grauOfVertex(self, v):
        return len(self.adjList[v])
    
    def printAdjList(self):
        for v in self.adjList:
            print(self.adjList[v])

    def isSimple(self):
        if self.parallelEdges():
            return False
        return True
    
    def isNull(self):
        return( "not implemented")
    
    def isRegular(self):
        return( "not implemented")
    
    def areIsomorphs(G1, G2):
        return( "not implemented")
    
    def isConnected(self):
        return( "not implemented")
    
    def areComplementary(G1, G2):
        return( "not implemented")
    
    def isComplete(self):
        return( "not implemented")
    
    def isolatedVertexex():
        return( "not implemented")
    
    def hasPendingVertex():
        return( "not implemented")
    
    def isCircuit(self):
        return( "not implemented")

In [118]:
g1 = Graph("n3e2(in).csv")
print("n =", g1.numVertices(), "\te =", g1.numArestas() )

n = 3 	e = 2

In [123]:
#g1.add_edge(1,1)
#g1.printAdjList()

print("loop {}".format(g1.loopEdges()))
print("paralel {}".format(g1.parallelEdges()))
g1.adjList.items()

loop {1: [0, 1, 1, 1, 1]}
paralel {1: [0, 1, 1, 1, 1]}

dict_items([(0, [1, 2]), (1, [0, 1, 1, 1, 1]), (2, [0])])

In [90]:
g1.add_edge(0,2)

In [87]:
g2 = Graph("n4e5(in).csv")
print("n =", g2.numVertices(), "\te =", g2.numArestas() )

n = 4 	e = 5

In [89]:
g2.printAdjList()

[1, 2]
[0, 2, 3]
[0, 1, 3]
[1, 2]

In [63]:
g3 = Graph("K5(in).csv")
print("n =", g3.numVertices(), "\te =", g3.numArestas() )

n = 5 	e = 10

---

### Matriz de adjacências

In [11]:
#Abre matriz de adjacencia sem rotulos

K5 = pd.read_csv("graphs/K5(in).csv", sep=';', header=None, engine='python')
K5

   0  1  2  3  4
0  A  B  C  D  E
1  0  1  1  1  1
2  1  0  1  1  1
3  1  1  0  1  1
4  1  1  1  0  1
5  1  1  1  1  0

In [12]:
#Abre matriz de adjacencia com rotulos

n3e2 = pd.read_csv(folder+"n3e2(in).csv", sep=';', header=0, engine='python')
n3e2

   A  B  C
0  0  1  1
1  1  0  0
2  1  0  0

In [13]:
#Abre matriz de adjacencia com rotulos

n4e5 = pd.read_csv(folder+"n4e5(in).csv", sep=';', header=0, engine='python')
n4e5

     A  B  C  D
A    0  1  1  0
B    1  0  1  1
C    1  1  0  1
D    0  1  1  0

### Implementacoes basicas

In [14]:
n = len(K5.index)
print("Numero de vertices:", n)

Numero de vertices: 6

In [23]:
heap = Graph("heap.csv")

In [28]:
g1.print_matrix()

A
B
C

In [ ]:
e = (heap.sum(axis=0).sum() / 2)
print("Numero de arestas:", e)

Numero de arestas: 5.0

In [ ]:
dG = n4e5.sum(axis=0)
print("Graus dos vertices:", np.array(dG))

Graus dos vertices: [2 3 3 2]